spring:
  application:
    name: ag-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/smartboat/springCloudConfig

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 7773


