spring:
  application:
    name: ag-gate
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 7771
zuul:
  prefix: /api
  routes:
    user-center:
      path: /user/**
      serviceId: ag-uc
jwt:
  expire: 3600
  pri-key:
    path: E:\\workspaces\\ag-demo\\cg-zuul\\src\\test\\resources\\pri.key
  pub-key:
    path: E:\\workspaces\\ag-demo\\cg-zuul\\src\\test\\resources\\pub.key