spring:
  application:
    name: ag-gate
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 7771
zuul:
  prefix: /api
  routes:
    user-center:
      path: /uc/**
      serviceId: user-center
