spring:
  application:
    name: ag-gate
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 7771
zuul:
  prefix: /api
  routes:
    user-center:
      path: /uc/**
      serviceId: ag-uc
    auth-server:
      path: /auth/**
      serviceId: ag-auth
jwt:
  token-header: access-token
  ignore-url: /auth/jwt
  pub-key:
    path: E:\\workspaces\\ag-demo\\cg-zuul\\src\\main\\resources\\pub.key

client:
  token-header: client-token
  id: ag-gate
  secret: 123456